import {hierarchy, type HierarchyNode} from 'd3-hierarchy';
import {polygonArea, polygonCentroid} from 'd3-polygon';
import {voronoiTreemap} from 'd3-voronoi-treemap';
import Papa from 'papaparse';
import {isFontData} from './fonts';
export interface Row {id:string;name:string;group:string;value:string;color?:string}
export interface Settings {title:string;subtitle:string;shape:string;palette:string;background:string;border:string;gap:number;groupBorder:number;fontSize:number;titleFontSize:number;subtitleFontSize:number;valueFontSize:number;fontName:string;fontData:string;labels:boolean;values:boolean;percent:boolean;legend:boolean;dark:boolean;seed:number;precision:number;width:number;height:number;scale:number;unit:string}
export const defaults:Settings={title:'بودجهٔ یک زندگی متعادل',subtitle:'توزیع هزینه‌های ماهانه · داده‌های نمونه',shape:'circle',palette:'garden',background:'#ffffff',border:'#ffffff',gap:3,groupBorder:5,fontSize:17,titleFontSize:25,subtitleFontSize:13,valueFontSize:14,fontName:'',fontData:'',labels:true,values:false,percent:true,legend:true,dark:false,seed:14,precision:0.005,width:1000,height:760,scale:2,unit:'میلیون تومان'};
export const palettes:Record<string,string[]>={garden:['#147d70','#58a58a','#a1cba2','#d7dda5','#e4b960','#d88d66','#a46c7c','#7f83a5'],ocean:['#185977','#2786a2','#54b3c0','#91d3c7','#566a9e','#a4b3d8'],sunset:['#a44957','#cf685c','#e49162','#edbf76','#c89b9f','#8d7299'],mono:['#184c43','#286959','#468674','#76a58d','#adc4ad','#d3dfcd']};
export function safeSettings(input:unknown):Settings {const s={...defaults};if(!input||typeof input!=='object')return s;const x=input as Record<string,unknown>;for(const k of ['title','subtitle','unit'] as const)if(typeof x[k]==='string')s[k]=x[k].slice(0,200);for(const k of ['labels','values','percent','legend','dark'] as const)if(typeof x[k]==='boolean')s[k]=x[k];for(const k of ['background','border'] as const)if(typeof x[k]==='string'&&/^#[a-f\d]{6}$/i.test(x[k]))s[k]=x[k];if(typeof x.palette==='string'&&Object.hasOwn(palettes,x.palette))s.palette=x.palette;if(typeof x.shape==='string'&&['circle','rectangle','hexagon'].includes(x.shape))s.shape=x.shape;if(isFontData(x.fontData)){s.fontData=x.fontData;s.fontName=typeof x.fontName==='string'?x.fontName.slice(0,100):'فونت دلخواه';}const bounds={gap:[0,12],groupBorder:[0,15],fontSize:[8,60],titleFontSize:[12,60],subtitleFontSize:[8,36],valueFontSize:[8,48],seed:[0,1000000],precision:[0.0001,0.1],width:[400,2400],height:[400,2400],scale:[1,3]};for(const key of Object.keys(bounds) as (keyof typeof bounds)[]){const v=x[key];if(typeof v==='number'&&Number.isFinite(v)&&v>=bounds[key][0]&&v<=bounds[key][1])s[key]=v;}return s;}
export const sample:Row[]=[['مسکن','ضروری','35'],['خواربار','ضروری','18'],['حمل‌ونقل','ضروری','8'],['سلامت','ضروری','6'],['سرمایه‌گذاری','آینده','14'],['پس‌انداز','آینده','9'],['آموزش','رشد','7'],['کتاب','رشد','3'],['سفر','سبک زندگی','8'],['تفریح','سبک زندگی','5'],['ورزش','سبک زندگی','4']].map(([name,group,value],i)=>({id:String(i),name,group,value}));
export const fa=(n:number,digits=0)=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:digits}).format(n);
export function number(value:unknown):number {const s=String(value??'').trim().replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[٬,\s]/g,'').replace(/٫/g,'.');return s?Number(s):NaN;}
export function validate(rows:Row[]):string[] {const errors:string[]=[];if(!rows.length)errors.push('حداقل یک ردیف داده وارد کنید.');if(rows.length>150)errors.push('حداکثر ۱۵۰ ردیف در هر نمودار مجاز است.');rows.forEach((r,i)=>{if(!r.name.trim())errors.push(`نام ردیف ${fa(i+1)} خالی است.`);if(!Number.isFinite(number(r.value))||number(r.value)<=0)errors.push(`مقدار ردیف ${fa(i+1)} باید عدد مثبت باشد.`);if(r.color&&!/^#[a-f\d]{6}$/i.test(r.color))errors.push(`رنگ ردیف ${fa(i+1)} معتبر نیست.`);});return errors;}
export function parseRows(text:string):Row[]{let data:unknown;if(text.trim().startsWith('[')){data=JSON.parse(text);}else{const p=Papa.parse<Record<string,string>>(text.trim(),{header:true,skipEmptyLines:true});if(p.errors.length)throw new Error('ساختار فایل CSV صحیح نیست.');data=p.data;}if(!Array.isArray(data))throw new Error('داده باید آرایه‌ای از ردیف‌ها باشد.');const rows=data.map((r,i)=>{if(!r||typeof r!=='object')throw new Error('ردیف داده نامعتبر است.');const x=r as Record<string,unknown>;return {id:String(i),name:String(x.name??x['نام']??''),group:String(x.group??x['گروه']??'بدون گروه'),value:String(x.value??x['مقدار']??''),color:x.color?String(x.color):undefined};});const errors=validate(rows);if(errors.length)throw new Error(errors[0]);return rows;}
interface Datum {name:string;children?:Datum[];row?:Row;value?:number}
type Node=HierarchyNode<Datum>&{polygon?:[number,number][]};
export interface Cell {row:Row;polygon:[number,number][];center:[number,number];color:string;value:number;area:number}
export interface Chart {cells:Cell[];groups:{name:string;polygon:[number,number][];color:string}[];error:number;total:number}
function random(seed:number){let a=seed;return ()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
export function compute(rows:Row[],s:Settings,focus=''):Chart {const errors=validate(rows);if(errors.length)throw new Error(errors[0]);const selected=focus?rows.filter(r=>(r.group||'بدون گروه')===focus):rows;const groups=[...new Set(selected.map(r=>r.group||'بدون گروه'))];const data:Datum={name:'root',children:groups.map(g=>({name:g,children:selected.filter(r=>(r.group||'بدون گروه')===g).map(row=>({name:row.name,row,value:number(row.value)}))}))};const root=hierarchy(data).sum(d=>d.value??0);const w=s.width,h=s.height;const topPadding=Math.max(115,s.titleFontSize+s.subtitleFontSize+35);const radius=Math.min(w-110,h-topPadding-55)/2;const cx=w/2,cy=(h+topPadding-55)/2;const sides=s.shape==='hexagon'?6:72;const clip:[number,number][]=s.shape==='rectangle'?[[55,topPadding],[w-55,topPadding],[w-55,h-55],[55,h-55]]:Array.from({length:sides},(_,i)=>{const angle=2*Math.PI*i/sides-Math.PI/2;return[cx+radius*Math.cos(angle),cy+radius*Math.sin(angle)];});
voronoiTreemap().clip(clip).prng(random(s.seed)).convergenceRatio(s.precision).maxIterationCount(180).minWeightRatio(0.00001)(root as HierarchyNode<unknown>);
const colors=palettes[s.palette]??palettes.garden,total=root.value??0,fullArea=Math.abs(polygonArea(clip));const cells:Cell[]=root.leaves().map((n,i)=>{const node=n as Node;if(!node.polygon||!node.data.row)throw new Error('محاسبهٔ نمودار کامل نشد. بذر چیدمان را تغییر دهید.');return {row:node.data.row,polygon:node.polygon,center:polygonCentroid(node.polygon),color:node.data.row.color??colors[groups.indexOf(node.parent?.data.name??'')%colors.length],value:node.value??0,area:Math.abs(polygonArea(node.polygon))};});const error=cells.reduce((sum,c)=>sum+Math.abs(c.area/fullArea-c.value/total),0)/2;return {cells,groups:(root.children??[]).map((n,i)=>({name:n.data.name,polygon:(n as Node).polygon??[],color:colors[i%colors.length]})),error,total};}

